// Core classes
export { Grapher } from './grapher.js';
export { EventEmitter } from './event-emitter.js';

// Types
export type {
  FncFormula,
  OnPlayPauseFn,
  OnTimeUpdateFn,
  OnCoordUpdateFn,
  OnFormulaErrorFn,
  GrapherOnEventFunctions,
  GrapherTheme,
  Formula,
  Variable,
  VisualizerState,
  FunctionParam,
  FunctionData,
} from './types.js';

// Constants and themes
export {
  defaultFormulas,
  defaultVariables,
  defaultVisualizer,
  emptyFormula,
  exampleFormulas1,
  exampleFormulas2,
  exampleFormulas3,
  darkTheme,
  lightTheme,
  FUNCS,
  kPHI,
  kBlackList,
  symbolSubs,
  mapFormulaStringArray,
  sortById as sortByIdConstant,
} from './constants.js';

// Mathematical functions
export {
  stepNaN,
  clamp,
  saturate,
  remap,
  smoothstep,
  ssign,
  radians,
  degrees,
  inversesqrt,
  rsqrt,
  rcbrt,
  rcp,
  fma,
  step,
  mix,
  lerp,
  over,
  tri,
  sqr,
  frac,
  fract,
  exp2,
  exp10,
  mod,
  cellnoise,
  voronoi,
  noise,
  c1,
  c2,
  c3,
  c4,
  c5,
  bounceOut,
  linear,
  easeInQuad,
  easeOutQuad,
  easeInOutQuad,
  easeInCubic,
  easeOutCubic,
  easeInOutCubic,
  easeInQuart,
  easeOutQuart,
  easeInOutQuart,
  easeInQuint,
  easeOutQuint,
  easeInOutQuint,
  easeInSine,
  easeOutSine,
  easeInOutSine,
  easeInExpo,
  easeOutExpo,
  easeInOutExpo,
  easeInCirc,
  easeOutCirc,
  easeInOutCirc,
  easeInBack,
  easeOutBack,
  easeInOutBack,
  easeInElastic,
  easeOutElastic,
  easeInOutElastic,
  easeInBounce,
  easeOutBounce,
  easeInOutBounce,
  mathFunctions,
} from './math-functions.js';

// Utilities
export { getErrorMessage, isBadNum, sortById } from './utils.js';